# Generated by Django 5.2.13 on 2026-04-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlcSchemaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('plc_host', models.CharField(default='127.0.0.1', max_length=255)),
                ('plc_port', models.PositiveIntegerField(default=502)),
                ('modbus_unit_id', models.PositiveIntegerField(default=1)),
                ('status_address', models.PositiveIntegerField(default=0)),
                ('status_count', models.PositiveIntegerField(default=12)),
                ('live_record_address', models.PositiveIntegerField(default=100)),
                ('live_record_count', models.PositiveIntegerField(default=48)),
                ('history_base_address', models.PositiveIntegerField(default=300)),
                ('history_record_words', models.PositiveIntegerField(default=34)),
                ('history_capacity', models.PositiveIntegerField(default=100)),
                ('cmd_circuit_select', models.PositiveIntegerField(default=1000)),
                ('cmd_start_request', models.PositiveIntegerField(default=1001)),
                ('cmd_stop_request', models.PositiveIntegerField(default=1002)),
                ('cmd_abort_request', models.PositiveIntegerField(default=1003)),
                ('cmd_test_phase', models.PositiveIntegerField(default=1004)),
                ('cmd_test_active', models.PositiveIntegerField(default=1005)),
                ('cmd_time_sync_request', models.PositiveIntegerField(default=1010)),
                ('cmd_time_sync_unix_high', models.PositiveIntegerField(default=1011)),
                ('cmd_time_sync_unix_low', models.PositiveIntegerField(default=1012)),
            ],
            options={
                'verbose_name': 'PLC Schema Config',
                'verbose_name_plural': 'PLC Schema Config',
            },
        ),
        migrations.CreateModel(
            name='TagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag_id', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('scale', models.CharField(choices=[('none', 'No Scale'), ('x10', 'x10'), ('x100', 'x100'), ('x1000', 'x1000')], default='x10', max_length=20)),
                ('register_type', models.CharField(choices=[('holding', 'Holding Register'), ('input', 'Input Register')], default='holding', max_length=20)),
                ('source_block', models.CharField(choices=[('live', 'Live Record'), ('history', 'History Record'), ('status', 'Status Block')], default='live', max_length=20)),
                ('data_type', models.CharField(choices=[('int16', 'INT16'), ('uint16', 'UINT16'), ('int32', 'INT32'), ('uint32', 'UINT32'), ('float32', 'FLOAT32')], default='int16', max_length=20)),
                ('word_order', models.CharField(choices=[('high_low', 'High Word / Low Word'), ('low_high', 'Low Word / High Word')], default='high_low', max_length=20)),
                ('modbus_address', models.PositiveIntegerField(default=0)),
                ('register_offset', models.PositiveIntegerField()),
                ('circuit_scope', models.CharField(choices=[('shared', 'Shared'), ('circuit1', 'Circuit 1'), ('circuit2', 'Circuit 2')], default='shared', max_length=20)),
                ('chart_group', models.CharField(default='temperature', max_length=64)),
                ('chart_group_title', models.CharField(blank=True, default='', max_length=255)),
                ('chart_group_title_en', models.CharField(blank=True, default='', max_length=255)),
                ('chart_color', models.CharField(default='#2563eb', max_length=16)),
                ('validity_bit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('simulation_enabled', models.BooleanField(default=True)),
                ('simulation_base', models.IntegerField(default=0)),
                ('simulation_amplitude', models.IntegerField(default=0)),
                ('simulation_wave', models.CharField(choices=[('fast', 'Fast'), ('slow', 'Slow')], default='slow', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('include_in_limits', models.BooleanField(default=True)),
                ('include_in_reports', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('source_block', 'modbus_address', 'register_offset', 'tag_id'),
            },
        ),
    ]
