# Generated by Django 5.2.13 on 2026-04-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlcRuntimeState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('plc_ready', models.BooleanField(default=False)),
                ('plc_fault', models.BooleanField(default=False)),
                ('buf_write_index', models.PositiveIntegerField(default=0)),
                ('buf_record_count', models.PositiveIntegerField(default=0)),
                ('buf_buffer_size', models.PositiveIntegerField(default=100)),
                ('buf_last_sequence_no', models.PositiveIntegerField(default=0)),
                ('plc_current_unix', models.BigIntegerField(default=0)),
                ('live_record_json', models.JSONField(blank=True, default=dict)),
                ('status_json', models.JSONField(blank=True, default=dict)),
                ('monitoring_active', models.BooleanField(default=False)),
                ('connection_ok', models.BooleanField(default=False)),
                ('stale_data', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_history_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_overrun_at', models.DateTimeField(blank=True, null=True)),
                ('last_time_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_time_sync_drift_sec', models.IntegerField(default=0)),
                ('communication_loss_since', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'PLC Runtime State',
            },
        ),
        migrations.CreateModel(
            name='PlcEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('OVERRUN', 'Overrun'), ('COMMUNICATION', 'Communication'), ('TIME_SYNC', 'Time_Sync')], max_length=20)),
                ('event_code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('test_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plc_events', to='tests.testrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
