# Generated by Django 5.2.13 on 2026-04-16 21:18

import apps.core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('products', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_no', models.CharField(max_length=50, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
                ('selected_circuit', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Circuit 1'), (2, 'Circuit 2'), (3, 'Circuit 1 + Circuit 2')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('START_REQUESTED', 'Start Requested'), ('RUNNING', 'Running'), ('COMPLETED_PASS', 'Completed Pass'), ('COMPLETED_FAIL', 'Completed Fail'), ('ABORTED', 'Aborted'), ('FAILED_TO_START', 'Failed To Start')], default=apps.core.constants.TestStatus['DRAFT'], max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stable_started_at', models.DateTimeField(blank=True, null=True)),
                ('stop_started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('recipe_name_snapshot', models.CharField(max_length=255)),
                ('recipe_code_snapshot', models.CharField(max_length=64)),
                ('recipe_revision_snapshot', models.CharField(max_length=32)),
                ('start_duration_sec_snapshot', models.PositiveIntegerField()),
                ('stable_duration_sec_snapshot', models.PositiveIntegerField()),
                ('stop_duration_sec_snapshot', models.PositiveIntegerField()),
                ('phase_context_sec_snapshot', models.PositiveIntegerField(default=5)),
                ('prestart_samples_json', models.JSONField(blank=True, default=list)),
                ('limits_snapshot_json', models.JSONField(default=dict)),
                ('result_passed', models.BooleanField(blank=True, null=True)),
                ('abort_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('fail_reason_summary', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='companies.company')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='products.productmodel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='recipes.recipe')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_code', models.CharField(max_length=100)),
                ('parameter_name', models.CharField(max_length=255)),
                ('phase_used', models.CharField(choices=[('START', 'Start'), ('STABLE', 'Stable'), ('STOP', 'Stop')], default=apps.core.constants.EvaluationPhase['STABLE'], max_length=20)),
                ('avg_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('min_enabled', models.BooleanField(default=False)),
                ('min_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('max_enabled', models.BooleanField(default=False)),
                ('max_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('passed', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='tests.testrecord')),
            ],
            options={
                'ordering': ('parameter_code',),
            },
        ),
        migrations.CreateModel(
            name='TestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_no', models.PositiveIntegerField()),
                ('timestamp_unix', models.BigIntegerField()),
                ('test_phase', models.PositiveSmallIntegerField(choices=[(0, 'Idle'), (1, 'Start'), (2, 'Stable'), (3, 'Stop'), (4, 'Manual'), (5, 'Aborted')])),
                ('status_word', models.PositiveIntegerField()),
                ('validity_word1', models.PositiveIntegerField()),
                ('validity_word2', models.PositiveIntegerField(blank=True, null=True)),
                ('dynamic_values', models.JSONField(blank=True, default=dict)),
                ('test_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='tests.testrecord')),
            ],
            options={
                'ordering': ('timestamp_unix', 'sequence_no'),
                'unique_together': {('test_record', 'sequence_no')},
            },
        ),
    ]
