# Generated by Django 5.2.13 on 2026-04-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('revision_no', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('start_duration_sec', models.PositiveIntegerField()),
                ('stable_duration_sec', models.PositiveIntegerField()),
                ('stop_duration_sec', models.PositiveIntegerField()),
                ('phase_context_sec', models.PositiveIntegerField(default=5)),
                ('limits_json', models.JSONField(default=dict)),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='products.productmodel')),
            ],
            options={
                'ordering': ['recipe_code', '-updated_at'],
            },
        ),
    ]
